# apiVersion: v1
# data:
#   mapRoles: |
#     - groups:
#       - system:bootstrappers
#       - system:nodes
#       rolearn: arn:aws:iam::151626788817:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WSU3FGQQ91S2
#       username: system:node:{{EC2PrivateDNSName}}
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2021-11-11T15:03:30Z"
#   name: aws-auth
#   namespace: kube-system
#   resourceVersion: "1443"
#   uid: cb1722bf-ed65-4b20-b415-d951390bdd75

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::151626788817:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-WSU3FGQQ91S2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::151626788817:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-11T15:03:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1443"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cb1722bf-ed65-4b20-b415-d951390bdd75
